const CREATE_ELEMENT = 'CREATE_ELEMENT'
const UPDATE_ELEMENT = 'UPDATE_ELEMENT'
const DELETE_ELEMENT = 'DELETE_ELEMENT'
const SET_FILTER = 'SET_FILTER'

export const state = () => ({
  list: [
    {
    "id": 1051,
    "name": "Fuerteventura Airport",
    "city": "Fuerteventura",
    "country": "Spain",
    "iata": "FUE",
    "icao": "GCFV",
    "latitude": 28.452699661254883,
    "longitude": -13.863800048828125,
    "altitude": 85,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1052,
    "name": "Hierro Airport",
    "city": "Hierro",
    "country": "Spain",
    "iata": "VDE",
    "icao": "GCHI",
    "latitude": 27.814800262451172,
    "longitude": -17.887100219726562,
    "altitude": 103,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1053,
    "name": "La Palma Airport",
    "city": "Santa Cruz De La Palma",
    "country": "Spain",
    "iata": "SPC",
    "icao": "GCLA",
    "latitude": 28.626499,
    "longitude": -17.7556,
    "altitude": 107,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1054,
    "name": "Gran Canaria Airport",
    "city": "Gran Canaria",
    "country": "Spain",
    "iata": "LPA",
    "icao": "GCLP",
    "latitude": 27.931900024414062,
    "longitude": -15.38659954071045,
    "altitude": 78,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1055,
    "name": "Lanzarote Airport",
    "city": "Arrecife",
    "country": "Spain",
    "iata": "ACE",
    "icao": "GCRR",
    "latitude": 28.945499,
    "longitude": -13.6052,
    "altitude": 46,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1056,
    "name": "Tenerife South Airport",
    "city": "Tenerife",
    "country": "Spain",
    "iata": "TFS",
    "icao": "GCTS",
    "latitude": 28.044500351,
    "longitude": -16.5725002289,
    "altitude": 209,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1057,
    "name": "Tenerife Norte Airport",
    "city": "Tenerife",
    "country": "Spain",
    "iata": "TFN",
    "icao": "GCXO",
    "latitude": 28.4827003479,
    "longitude": -16.3414993286,
    "altitude": 2076,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1058,
    "name": "Melilla Airport",
    "city": "Melilla",
    "country": "Spain",
    "iata": "MLN",
    "icao": "GEML",
    "latitude": 35.279800415,
    "longitude": -2.9562599659,
    "altitude": 156,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1211,
    "name": "Albacete-Los Llanos Airport",
    "city": "Albacete",
    "country": "Spain",
    "iata": "ABC",
    "icao": "LEAB",
    "latitude": 38.9485015869,
    "longitude": -1.8635200262099998,
    "altitude": 2302,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1212,
    "name": "Alicante International Airport",
    "city": "Alicante",
    "country": "Spain",
    "iata": "ALC",
    "icao": "LEAL",
    "latitude": 38.28219985961914,
    "longitude": -0.5581560134887695,
    "altitude": 142,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1213,
    "name": "Almería International Airport",
    "city": "Almeria",
    "country": "Spain",
    "iata": "LEI",
    "icao": "LEAM",
    "latitude": 36.84389877319336,
    "longitude": -2.3701000213623047,
    "altitude": 70,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1214,
    "name": "Asturias Airport",
    "city": "Aviles",
    "country": "Spain",
    "iata": "OVD",
    "icao": "LEAS",
    "latitude": 43.5635986328125,
    "longitude": -6.0346198081970215,
    "altitude": 416,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1215,
    "name": "Córdoba Airport",
    "city": "Cordoba",
    "country": "Spain",
    "iata": "ODB",
    "icao": "LEBA",
    "latitude": 37.84199905395508,
    "longitude": -4.848879814147949,
    "altitude": 297,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1216,
    "name": "Bilbao Airport",
    "city": "Bilbao",
    "country": "Spain",
    "iata": "BIO",
    "icao": "LEBB",
    "latitude": 43.30110168457031,
    "longitude": -2.9106099605560303,
    "altitude": 138,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1218,
    "name": "Barcelona International Airport",
    "city": "Barcelona",
    "country": "Spain",
    "iata": "BCN",
    "icao": "LEBL",
    "latitude": 41.2971,
    "longitude": 2.07846,
    "altitude": 12,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1219,
    "name": "Badajoz Airport",
    "city": "Badajoz",
    "country": "Spain",
    "iata": "BJZ",
    "icao": "LEBZ",
    "latitude": 38.891300201416016,
    "longitude": -6.8213300704956055,
    "altitude": 609,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1220,
    "name": "A Coruña Airport",
    "city": "La Coruna",
    "country": "Spain",
    "iata": "LCG",
    "icao": "LECO",
    "latitude": 43.302101,
    "longitude": -8.37726,
    "altitude": 326,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1221,
    "name": "Armilla Air Base",
    "city": "Granada",
    "country": "Spain",
    "iata": "",
    "icao": "LEGA",
    "latitude": 37.1332016,
    "longitude": -3.63568997,
    "altitude": 2297,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1222,
    "name": "Girona Airport",
    "city": "Gerona",
    "country": "Spain",
    "iata": "GRO",
    "icao": "LEGE",
    "latitude": 41.901000977,
    "longitude": 2.7605500221,
    "altitude": 468,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1223,
    "name": "Federico Garcia Lorca Airport",
    "city": "Granada",
    "country": "Spain",
    "iata": "GRX",
    "icao": "LEGR",
    "latitude": 37.18870162963867,
    "longitude": -3.777359962463379,
    "altitude": 1860,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1224,
    "name": "Getafe Air Base",
    "city": "Madrid",
    "country": "Spain",
    "iata": "",
    "icao": "LEGT",
    "latitude": 40.29410171508789,
    "longitude": -3.723829984664917,
    "altitude": 2031,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1225,
    "name": "Ibiza Airport",
    "city": "Ibiza",
    "country": "Spain",
    "iata": "IBZ",
    "icao": "LEIB",
    "latitude": 38.872898101800004,
    "longitude": 1.3731199502899998,
    "altitude": 24,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1226,
    "name": "Jerez Airport",
    "city": "Jerez",
    "country": "Spain",
    "iata": "XRY",
    "icao": "LEJR",
    "latitude": 36.744598388671875,
    "longitude": -6.060110092163086,
    "altitude": 93,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1227,
    "name": "San Javier Airport",
    "city": "Murcia",
    "country": "Spain",
    "iata": "MJV",
    "icao": "LELC",
    "latitude": 37.775001525878906,
    "longitude": -0.8123890161514282,
    "altitude": 11,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1229,
    "name": "Adolfo Suárez Madrid–Barajas Airport",
    "city": "Madrid",
    "country": "Spain",
    "iata": "MAD",
    "icao": "LEMD",
    "latitude": 40.471926,
    "longitude": -3.56264,
    "altitude": 1998,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1230,
    "name": "Málaga Airport",
    "city": "Malaga",
    "country": "Spain",
    "iata": "AGP",
    "icao": "LEMG",
    "latitude": 36.67490005493164,
    "longitude": -4.499110221862793,
    "altitude": 53,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1231,
    "name": "Menorca Airport",
    "city": "Menorca",
    "country": "Spain",
    "iata": "MAH",
    "icao": "LEMH",
    "latitude": 39.86259841918945,
    "longitude": 4.218649864196777,
    "altitude": 302,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1232,
    "name": "Moron Air Base",
    "city": "Sevilla",
    "country": "Spain",
    "iata": "OZP",
    "icao": "LEMO",
    "latitude": 37.17490005493164,
    "longitude": -5.615940093994141,
    "altitude": 285,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1233,
    "name": "Ocaña Airport",
    "city": "Ocana",
    "country": "Spain",
    "iata": "",
    "icao": "LEOC",
    "latitude": 39.9375,
    "longitude": -3.5033299922943115,
    "altitude": 2405,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1234,
    "name": "Pamplona Airport",
    "city": "Pamplona",
    "country": "Spain",
    "iata": "PNA",
    "icao": "LEPP",
    "latitude": 42.77000045776367,
    "longitude": -1.6463299989700317,
    "altitude": 1504,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1235,
    "name": "Alcantarilla Air Base",
    "city": "Murcia",
    "country": "Spain",
    "iata": "",
    "icao": "LERI",
    "latitude": 37.951099,
    "longitude": -1.23032,
    "altitude": 250,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1236,
    "name": "Reus Air Base",
    "city": "Reus",
    "country": "Spain",
    "iata": "REU",
    "icao": "LERS",
    "latitude": 41.14739990234375,
    "longitude": 1.1671700477600098,
    "altitude": 233,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1237,
    "name": "Rota Naval Station Airport",
    "city": "Rota",
    "country": "Spain",
    "iata": "ROZ",
    "icao": "LERT",
    "latitude": 36.645198822,
    "longitude": -6.34946012497,
    "altitude": 86,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1238,
    "name": "Salamanca Airport",
    "city": "Salamanca",
    "country": "Spain",
    "iata": "SLM",
    "icao": "LESA",
    "latitude": 40.95209884643555,
    "longitude": -5.501989841461182,
    "altitude": 2595,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1239,
    "name": "Son Bonet Airport",
    "city": "Son Bonet",
    "country": "Spain",
    "iata": "",
    "icao": "LESB",
    "latitude": 39.598899841308594,
    "longitude": 2.70278000831604,
    "altitude": 157,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1241,
    "name": "San Luis Airport",
    "city": "San Luis",
    "country": "Spain",
    "iata": "",
    "icao": "LESL",
    "latitude": 39.86220169067383,
    "longitude": 4.25832986831665,
    "altitude": 197,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1242,
    "name": "San Sebastian Airport",
    "city": "San Sebastian",
    "country": "Spain",
    "iata": "EAS",
    "icao": "LESO",
    "latitude": 43.35649871826172,
    "longitude": -1.7906099557876587,
    "altitude": 16,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1243,
    "name": "Santiago de Compostela Airport",
    "city": "Santiago",
    "country": "Spain",
    "iata": "SCQ",
    "icao": "LEST",
    "latitude": 42.89630126953125,
    "longitude": -8.415140151977539,
    "altitude": 1213,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1244,
    "name": "Pirineus - la Seu d'Urgel Airport",
    "city": "Seo De Urgel",
    "country": "Spain",
    "iata": "LEU",
    "icao": "LESU",
    "latitude": 42.3386,
    "longitude": 1.40917,
    "altitude": 2625,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1245,
    "name": "Torrejón Airport",
    "city": "Madrid",
    "country": "Spain",
    "iata": "TOJ",
    "icao": "LETO",
    "latitude": 40.496700286865234,
    "longitude": -3.4458699226379395,
    "altitude": 2026,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1246,
    "name": "Valencia Airport",
    "city": "Valencia",
    "country": "Spain",
    "iata": "VLC",
    "icao": "LEVC",
    "latitude": 39.4893,
    "longitude": -0.481625,
    "altitude": 240,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1247,
    "name": "Valladolid Airport",
    "city": "Valladolid",
    "country": "Spain",
    "iata": "VLL",
    "icao": "LEVD",
    "latitude": 41.7061004639,
    "longitude": -4.85194015503,
    "altitude": 2776,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1249,
    "name": "Vitoria/Foronda Airport",
    "city": "Vitoria",
    "country": "Spain",
    "iata": "VIT",
    "icao": "LEVT",
    "latitude": 42.8828010559082,
    "longitude": -2.7244699001312256,
    "altitude": 1682,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1250,
    "name": "Vigo Airport",
    "city": "Vigo",
    "country": "Spain",
    "iata": "VGO",
    "icao": "LEVX",
    "latitude": 42.2318000793457,
    "longitude": -8.62677001953125,
    "altitude": 856,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1251,
    "name": "Santander Airport",
    "city": "Santander",
    "country": "Spain",
    "iata": "SDR",
    "icao": "LEXJ",
    "latitude": 43.427101135253906,
    "longitude": -3.82000994682312,
    "altitude": 16,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1252,
    "name": "Zaragoza Air Base",
    "city": "Zaragoza",
    "country": "Spain",
    "iata": "ZAZ",
    "icao": "LEZG",
    "latitude": 41.66619873046875,
    "longitude": -1.0415500402450562,
    "altitude": 863,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 1253,
    "name": "Sevilla Airport",
    "city": "Sevilla",
    "country": "Spain",
    "iata": "SVQ",
    "icao": "LEZL",
    "latitude": 37.417999267578125,
    "longitude": -5.8931097984313965,
    "altitude": 112,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 3998,
    "name": "Palma De Mallorca Airport",
    "city": "Palma de Mallorca",
    "country": "Spain",
    "iata": "PMI",
    "icao": "LEPA",
    "latitude": 39.551700592,
    "longitude": 2.73881006241,
    "altitude": 27,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 5659,
    "name": "La Gomera Airport",
    "city": "La Gomera",
    "country": "Spain",
    "iata": "GMZ",
    "icao": "GCGM",
    "latitude": 28.029600143432617,
    "longitude": -17.214599609375,
    "altitude": 716,
    "timezone": 0,
    "DST": "E",
    "tz": "Atlantic/Canary",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 5781,
    "name": "Logroño-Agoncillo Airport",
    "city": "Logroño-Agoncillo",
    "country": "Spain",
    "iata": "RJL",
    "icao": "LELO",
    "latitude": 42.4609534888,
    "longitude": -2.32223510742,
    "altitude": 1161,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 6756,
    "name": "Leon Airport",
    "city": "Leon",
    "country": "Spain",
    "iata": "LEN",
    "icao": "LELN",
    "latitude": 42.5890007019043,
    "longitude": -5.65556001663208,
    "altitude": 3006,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 6757,
    "name": "Burgos Airport",
    "city": "Burgos",
    "country": "Spain",
    "iata": "RGS",
    "icao": "LEBG",
    "latitude": 42.357601,
    "longitude": -3.62076,
    "altitude": 2945,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 6868,
    "name": "Sabadell Airport",
    "city": "Sabadell",
    "country": "Spain",
    "iata": "QSA",
    "icao": "LELL",
    "latitude": 41.52090072631836,
    "longitude": 2.1050798892974854,
    "altitude": 485,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 7459,
    "name": "Lleida-Alguaire Airport",
    "city": "Lleida",
    "country": "Spain",
    "iata": "ILD",
    "icao": "LEDA",
    "latitude": 41.728185,
    "longitude": 0.535023,
    "altitude": 1170,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 7488,
    "name": "Huesca/Pirineos Airport",
    "city": "Huesca",
    "country": "Spain",
    "iata": "HSK",
    "icao": "LEHC",
    "latitude": 42.0760993958,
    "longitude": -0.316666990519,
    "altitude": 1768,
    "timezone": 1,
    "DST": "U",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 7489,
    "name": "Ciudad Real Central Airport",
    "city": "Ciudad Real",
    "country": "Spain",
    "iata": "CQM",
    "icao": "LERL",
    "latitude": 38.8563888889,
    "longitude": -3.97,
    "altitude": 0,
    "timezone": 1,
    "DST": "U",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 7731,
    "name": "La Cerdanya Airport",
    "city": "Das i Fontanals de Cerdanya",
    "country": "Spain",
    "iata": "",
    "icao": "LECD",
    "latitude": 42.38639831542969,
    "longitude": 1.86667001247406,
    "altitude": 3586,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 8690,
    "name": "Fuentemilanos Airport",
    "city": "Segovia",
    "country": "Spain",
    "iata": "",
    "icao": "LEFM",
    "latitude": 40.888610839799995,
    "longitude": -4.23750019073,
    "altitude": 3307,
    "timezone": 1,
    "DST": "E",
    "tz": "Europe/Madrid",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 11878,
    "name": "Cuatro Vientos Airport",
    "city": "Madrid",
    "country": "Spain",
    "iata": "ECV",
    "icao": "LECU",
    "latitude": 40.370701,
    "longitude": -3.78514,
    "altitude": 2269,
    "timezone": "",
    "DST": "",
    "tz": "",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 11879,
    "name": "Castellón-Costa Azahar Airport",
    "city": "Castellón de la Plana",
    "country": "Spain",
    "iata": "CDT",
    "icao": "LEDS",
    "latitude": 40.213889,
    "longitude": 0.073333,
    "altitude": 1145,
    "timezone": "",
    "DST": "",
    "tz": "",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 11880,
    "name": "Teruel Airport",
    "city": "Teruel",
    "country": "Spain",
    "iata": "TEV",
    "icao": "LETL",
    "latitude": 40.403,
    "longitude": -1.2183,
    "altitude": 3380,
    "timezone": "",
    "DST": "",
    "tz": "",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 13677,
    "name": "Algeciras Heliport",
    "city": "Algeciras",
    "country": "Spain",
    "iata": "AEI",
    "icao": "LEAG",
    "latitude": 36.12888,
    "longitude": -5.441118,
    "altitude": 98,
    "timezone": -2,
    "DST": "E",
    "tz": "",
    "type": "airport",
    "source": "OurAirports"
  },
  {
    "id": 13829,
    "name": "Región de Murcia International Airport",
    "city": "Murcia",
    "country": "Spain",
    "iata": "RMU",
    "icao": "LEMI",
    "latitude": 37.803,
    "longitude": -1.125,
    "altitude": 632,
    "timezone": 1,
    "DST": "E",
    "tz": "",
    "type": "airport",
    "source": "OurAirports"
  }
  ],
  filter: null
})

export const mutations = {
  [CREATE_ELEMENT](state, data) {
    data.id = state.list.slice(-1).pop().id + 1
    state.list.push(data)
  },
  [UPDATE_ELEMENT](state, data) {
    let index = state.list.findIndex(item => item.id == data.id);
    if (index > -1) {
      state.list.splice(index, 1);
      state.list.push(data)
    }
  },
  [DELETE_ELEMENT](state, id) {
    let index = state.list.findIndex(item => item.id == id);
    if (index > -1) {
      state.list.splice(index, 1);
    }
  },
  [SET_FILTER](state, data) {
    state.filter = data;
  }
}

export const actions = {

}

export const getters = {
}